[serviceweaver]
binary = "./kafkaless"

[single]
listeners.api = { address = "127.0.0.1:12345" }

[multi]
mtls = true
listeners.api = { address = "127.0.0.1:12345" }

["github.com/syllabix/kafkaless/producer/Service"]
Address = ["localhost:9092"]
Topic = "events"

["github.com/syllabix/kafkaless/consumer/Service"]
Brokers = ["localhost:9092"]
Topic = "events"
GroupID = "consumer-group-id"
